version: "3"
services:
  centos:
    build:
      context: ./centos/
    container_name: centos
    volumes:
      - ${SOURCE_DIR}:/www/:rw
    restart: always
    privileged: true
    networks:
      - default
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
  php74:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP74_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP74_EXTENSIONS}
        TZ: "$TZ"
    container_name: php74
    expose:
      - 9501
      # extra_hosts:
      # - "hogen.com:192.168.1.110"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP74_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP74_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP74_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
  mysql5:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: "$TZ"
    networks:
      - default
  # php56:
  #  build:
  #    context: ./services/php
  #    args:
  #      PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
  #      CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #      PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
  #      TZ: "$TZ"
  #  container_name: ${PROJECT_NAME}_php56
  #  expose:
  #    - 9501
  #  volumes:
  #    - ${SOURCE_DIR}:/www/:rw
  #    - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
  #    - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
  #    - ${PHP56_LOG_DIR}:/var/log/php
  #    - ${DATA_DIR}/composer:/tmp/composer
  #  restart: always
  #  cap_add:
  #    - SYS_PTRACE
  #  networks:
  #    - default
  # rabbitmq:
  #   container_name: ${PROJECT_NAME}_rabbitmq
  #   image: rabbitmq:management
  #   restart: always
  #   ports:
  #     - 5672:5672
  #     - 15671:15671
  #     - 15672:15672
  #     - 5671:5671
  #     - 25672:25672
  #   volumes:
  #     - ${SOURCE_DIR}:/www/:rw
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
  #     RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
networks:
  default:
