FROM rabbitmq:management

RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list

RUN  apt-get clean

RUN apt-get update && apt-get install -y python

ADD rabbitmqadmin /usr/local/bin/

RUN chmod +x /usr/local/bin/rabbitmqadmin